### ISSUE TITLE
roiPos error

### ISSUE THREAD

**Issue by lachioma** [fabiocarrara/meye#34]
In the Matlab version of Meye, I tried to replicate Example 3 from example.m but on an image of mine. 
When using
`ROI = [330,70,130,100];`
I get the following error:
```
Unable to perform assignment because the size of the left side is 130-by-100 and the size of the right
side is 100-by-130.

Error in Meye/predictImage (line 79)
                pupilMask(roiPos(2):roiPos(2)+roiPos(3)-1,...
```

I think that lines 79 and 80 of Meye.m contain an error with the indices of roiPos and should be changed to:
```
pupilMask(roiPos(2):roiPos(2)+roiPos(4)-1,...
      roiPos(1):roiPos(1)+roiPos(3)-1) = imresize(rawMask, [roiPos(4), roiPos(3)],"bilinear");
```
Now it runs but I think there is still something wrong.

**Comment by fabiocarrara** [comment]
thanks for bringing this up. @LeonardoLupori can you check this?

**Comment by LeonardoLupori** [comment]
Hi @lachioma !

Thanks a lot for pointing this out.

As you already saw, I got the order of width and height wrong in 2 places: both where you pointed and when creating the crop.

I already created a pull request that should solve the issue. You should get an update as soon as it is merged. 
Let us know whether it also works for you!

All the best,
Leo

**Comment by fabiocarrara** [comment]
#35 merged, thanks @LeonardoLupori .

@lachioma feel free to close if this solves your problem.

**Comment by lachioma** [comment]
Thank you!
