### ISSUE TITLE
Camera source on online version

### ISSUE THREAD

**Issue by patricio1979** [fabiocarrara/meye#37]
It would be very useful to choose camera source to online version. I need to select a non built-in camera for processing.

Thank you

**Comment by fabiocarrara** [comment]
Yes, it would be handy, but you should be able to select the default camera (either globally or per-site) in the settings of your browser.On Sep 19, 2022 20:56, Patricio ***@***.***> wrote:
It would be very useful to choose camera source to online version. I need to select a non built-in camera for processing.
Thank you

**Comment by patricio1979** [comment]
Yes, I guess this feature request should be in Opera's github.

Thank you
